var samples = {
	nonword: [
		{key:'Dorfultariant', value: 'Red'},
		{key:'Adloot', value: 'Orange'},
		{key:'Aswelly', value: 'Yellow'},
		{key:'Refleep', value: 'Green'},
		{key:'Nalpure', value: 'Blue'},
		{key:'Hundined', value: 'Purple'},
		{key:'Chillaid', value: 'Black'},
		
		{key:'Adloot', value: 'Red'},
		{key:'Aswelly', value: 'Orange'},
		{key:'Refleep', value: 'Yellow'},
		{key:'Nalpure', value: 'Green'},
		{key:'Hundined', value: 'Blue'},
		{key:'Chillaid', value: 'Purple'},
		{key:'Dorfultariant', value: 'Black'},
		
		{key:'Aswelly', value: 'Red'},
		{key:'Refleep', value: 'Orange'},
		{key:'Nalpure', value: 'Yellow'},
		{key:'Hundined', value: 'Green'},
		{key:'Chillaid', value: 'Blue'},
		{key:'Dorfultariant', value: 'Purple'},
		{key:'Adloot', value: 'Black'},
		
		{key:'Refleep', value: 'Red'},
		{key:'Nalpure', value: 'Orange'},
		{key:'Hundined', value: 'Yellow'},
		{key:'Chillaid', value: 'Green'},
		{key:'Dorfultariant', value: 'Blue'},
		{key:'Adloot', value: 'Purple'},
		{key:'Aswelly', value: 'Black'},
		
		{key:'Nalpure', value: 'Red'},
		{key:'Hundined', value: 'Orange'},
		{key:'Chillaid', value: 'Yellow'},
		{key:'Dorfultariant', value: 'Green'},
		{key:'Adloot', value: 'Blue'},
		{key:'Aswelly', value: 'Purple'},
		{key:'Refleep', value: 'Black'},
		
		{key:'Hundined', value: 'Red'},
		{key:'Chillaid', value: 'Orange'},
		{key:'Dorfultariant', value: 'Yellow'},
		{key:'Adloot', value: 'Green'},
		{key:'Aswelly', value: 'Blue'},
		{key:'Refleep', value: 'Purple'},
		{key:'Nalpure', value: 'Black'},
		
		{key:'Black', value: 'Red'},
		{key:'Dorfultariant', value: 'Orange'},
		{key:'Adloot', value: 'Yellow'},
		{key:'Aswelly', value: 'Green'},
		{key:'Refleep', value: 'Blue'},
		{key:'Nalpure', value: 'Purple'},
		{key:'Hundined', value: 'Black'}
	],

	colorword: [
		{key:'Red', value: 'Red'},
		{key:'Orange', value: 'Orange'},
		{key:'Yellow', value: 'Yellow'},
		{key:'Green', value: 'Green'},
		{key:'Blue', value: 'Blue'},
		{key:'Purple', value: 'Purple'},
		{key:'Black', value: 'Black'},
		
		{key:'Orange', value: 'Red'},
		{key:'Yellow', value: 'Orange'},
		{key:'Green', value: 'Yellow'},
		{key:'Blue', value: 'Green'},
		{key:'Purple', value: 'Blue'},
		{key:'Black', value: 'Purple'},
		{key:'Red', value: 'Black'},
		
		{key:'Yellow', value: 'Red'},
		{key:'Green', value: 'Orange'},
		{key:'Blue', value: 'Yellow'},
		{key:'Purple', value: 'Green'},
		{key:'Black', value: 'Blue'},
		{key:'Red', value: 'Purple'},
		{key:'Orange', value: 'Black'},
		
		{key:'Green', value: 'Red'},
		{key:'Blue', value: 'Orange'},
		{key:'Purple', value: 'Yellow'},
		{key:'Black', value: 'Green'},
		{key:'Red', value: 'Blue'},
		{key:'Orange', value: 'Purple'},
		{key:'Yellow', value: 'Black'},
		
		{key:'Blue', value: 'Red'},
		{key:'Purple', value: 'Orange'},
		{key:'Black', value: 'Yellow'},
		{key:'Red', value: 'Green'},
		{key:'Orange', value: 'Blue'},
		{key:'Yellow', value: 'Purple'},
		{key:'Green', value: 'Black'},
		
		{key:'Purple', value: 'Red'},
		{key:'Black', value: 'Orange'},
		{key:'Red', value: 'Yellow'},
		{key:'Orange', value: 'Green'},
		{key:'Yellow', value: 'Blue'},
		{key:'Green', value: 'Purple'},
		{key:'Blue', value: 'Black'},
		
		{key:'Black', value: 'Red'},
		{key:'Red', value: 'Orange'},
		{key:'Orange', value: 'Yellow'},
		{key:'Yellow', value: 'Green'},
		{key:'Green', value: 'Blue'},
		{key:'Blue', value: 'Purple'},
		{key:'Purple', value: 'Black'}
	],

	spanishWords: [
		{key:'escuela', value:'school'},
		{key:'manzana', value:'apple'},
		{key:'mesa', value:'table'},
		{key:'verde', value:'green'},
		{key:'nariz', value:'nose'},
		{key:'ciencia', value:'science'},
		{key:'biblioteca', value:'library'},
		{key:'médico', value:'doctor'},
		{key:'queso', value:'cheese'},
		{key:'puerta', value:'door'},
		{key:'coche', value:'car'},
		{key:'árbol', value:'tree'},
		{key:'playa', value:'beach'},
		{key:'brazo', value:'arm'},
		{key:'perro', value:'dog'},
		{key:'maestro', value:'teacher'},
		{key:'ojo', value:'eye'},
		{key:'ventana', value:'window'},
		{key:'azul', value:'blue'},
		{key:'rojo', value:'red'},
		{key:'gato', value:'cat'},
		{key:'libro', value:'book'},
		{key:'amarillo', value:'yellow'},
		{key:'blanco', value:'white'},
		{key:'boca', value:'mouth'},
		{key:'cabeza', value:'head'}
	]
};
